backend:
  name: git-gateway
  repo: jetlagguy/drstevejasper.com
  branch: master
  api_root: https://api.github.com
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"

publish_mode: editorial_workflow

media_folder: "images/uploads"
